# Generated by Django 5.1.3 on 2024-11-19 05:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('nationality', models.CharField(choices=[('IR', 'ایرانی'), ('NON_IR', 'غیر ایرانی')], max_length=10, verbose_name='Nationality')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport Number')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(default=0)),
                ('child_age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='تأیید قوانین و مقررات')),
                ('passenger_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.passengerdetail', verbose_name='full_name')),
                ('booking_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='اطلاعات رزرو')),
            ],
        ),
        migrations.AddField(
            model_name='passengerdetail',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.reservation', verbose_name='Reservation'),
        ),
    ]
