# Generated by Django 5.1.3 on 2024-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_child_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
