# Generated by Django 5.1.3 on 2024-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_paymentinfo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='passenger_info',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='booking_details',
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nationality',
            field=models.CharField(blank=True, choices=[('IR', 'ایرانی'), ('NON_IR', 'غیر ایرانی')], max_length=10, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport Number'),
        ),
        migrations.DeleteModel(
            name='PassengerDetail',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
