# Generated by Django 5.1.3 on 2024-12-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_paymentinfo_passenger_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='تأیید قوانین و مقررات')),
                ('reservation', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='اطلاعات رزرو')),
            ],
        ),
    ]
