# Generated by Django 5.1.3 on 2024-12-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_first_name_userprofile_last_name_and_more'),
        ('reservations', '0006_alter_paymentinfo_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='اطلاعات رزرو'),
        ),
    ]
