# Generated by Django 5.1.3 on 2024-12-03 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_first_name_userprofile_last_name_and_more'),
        ('reservations', '0008_paymentinfo_discount_price_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.userprofile'),
        ),
    ]
