# Generated by Django 5.1.3 on 2024-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'موفق')], default='pending', max_length=10, verbose_name='وضعیت رزرو'),
        ),
    ]
