# Generated by Django 5.1.3 on 2024-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_paymentinfo_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='discount_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SUCCESS', 'موفق')], default='pending', max_length=10, verbose_name='وضعیت رزرو'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت کل'),
        ),
    ]
