# Generated by Django 5.1.3 on 2024-11-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_city_alter_hotel_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
