# Generated by Django 5.1.3 on 2024-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='faqs',
            field=models.TextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='restaurants_and_cafes',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rules',
            field=models.TextField(),
        ),
    ]
