# Generated by Django 5.1.3 on 2024-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='faqs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='restaurants_and_cafes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
