# Generated by Django 5.1.3 on 2024-11-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='passenger_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.passengerdetail', verbose_name='full_name'),
        ),
    ]
