# Generated by Django 5.1.3 on 2024-12-07 06:30

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province'),
        ),
    ]
